version: '3'
services:
  frontend:
    command: sh -c "npm rebuild esbuild && npm run dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:10001:10001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    stdin_open: true

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:4001:4001"
    depends_on:
      - database
    volumes:
      - ./backend:/app

  database:
    image: postgres
    ports:
      - "0.0.0.0:6001:5432"
    restart: always
    environment:
      - POSTGRES_DB=TodoDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - database

volumes:
  postgres-data: